### ISSUE TITLE
structure of setting file

### ISSUE THREAD

**Issue by lepture** [avelino/liquidluck#51]
in yaml:

``` yaml
site:
    name: Just lepture
    url: http://lepture.com

config:
    source: content
    output: deploy
    static: deploy/static
    static_prefix: /static/
    permalink: "{{category}}/{{filename}}.html"
    relative_url: false
    timezone: +08:00

author:
    default: admin
    vars:
        admin:
            fullname: Web Master
            email: master@web.com
        lepture:
            fullname: Hsiaoming Yang
            website: me@lepture.com


theme:
    active:
        - moment
        - bootstrap
    vars:
        navigation:
            -
                title: About
                url: /about
            -
                title: Resume
                url: /resume

writer:
    active:
        - liquidluck.writers.core.PostWriter
        - liquidluck.writers.core.ArchiveWriter
    vars:

reader:
    active:
        - liquidluck.readers.markdown.MarkdownReader
    vars:
```
